export XDG_DESKTOP_DIR="$HOME/docs"
export XDG_DOCUMENTS_DIR="$HOME/docs"
export XDG_DOWNLOAD_DIR="$HOME/dl"
export XDG_MUSIC_DIR="$HOME/media/music"
export XDG_PICTURES_DIR="$HOME/pics";
export XDG_PUBLICSHARE_DIR="$HOME/media/public"
export XDG_TEMPLATES_DIR="$HOME/docs/templates"
export XDG_VIDEOS_DIR="$HOME/media/video"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export PATH="$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export TERMINAL="kitty"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/pythonrc"
export GOPATH="$XDG_DATA_HOME/go"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

HISTFILE="$HOME/.cache/history"
HISTSIZE=1000000
SAVEHIST=1000000
