export PATH="$HOME/.local/bin:$PATH"
export EDITOR="nvim"

XDG_DESKTOP_DIR="$HOME/docs"
XDG_DOCUMENTS_DIR="$HOME/docs"
XDG_DOWNLOAD_DIR="$HOME/dl"
XDG_MUSIC_DIR="$HOME/media/music"
XDG_PICTURES_DIR="$HOME/pics"
XDG_PUBLICSHARE_DIR="$HOME/media/public"
XDG_TEMPLATES_DIR="$HOME/docs/templates"
XDG_VIDEOS_DIR="$HOME/media/rec"
