require('dashboard').setup ({
    theme = 'doom',
    config = {
      header = {
        '',
        '',
        '',
        '          ▀████▀▄▄              ▄█ ',
        '            █▀    ▀▀▄▄▄▄▄    ▄▄▀▀█ ',
        '    ▄        █          ▀▀▀▀▄  ▄▀  ',
        '   ▄▀ ▀▄      ▀▄              ▀▄▀  ',
        '  ▄▀    █     █▀   ▄█▀▄      ▄█    ',
        '  ▀▄     ▀▄  █     ▀██▀     ██▄█   ',
        '   ▀▄    ▄▀ █   ▄██▄   ▄  ▄  ▀▀ █  ',
        '    █  ▄▀  █    ▀██▀    ▀▀ ▀▀  ▄▀  ',
        '   █   █  █      ▄▄           ▄▀   ',
        '▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀',
        '',
      },
      center = {
        {
          icon_hl = '@variable',
          desc = ' Find files',
          group = 'Label',
          action = 'Telescope find_files',
          key = 'f',
          key_format = ' %s',
        },
        {
          desc = ' Open scripts',
          group = 'Label',
          action = 'edit ~/scripts/',
          key_format = ' %s',
          key = 's',
        },
        {
          desc = ' Open dotfiles',
          group = 'Number',
          action = 'edit ~/repos/dotfiles/',
          key = 'd',
          key_format = ' %s',
        },
        {
          desc = '󱠓 Change theme',
          group = 'label',
          action = 'Telescope colorscheme',
          key = 'c',
          key_format = ' %s',
        },
        { desc = '󰊳 Update plugins                    ',
          group = '@property',
          action = 'Lazy update',
          key = 'u',
          key_format = ' %s',
        },
      },
    footer = {" emacs users should never be trusted"}
    },
  })
